// Mermaid needs a layout engine, which happy-dom lacks, so these are real
// `mermaid.render` outputs captured in Chromium with the stylesheet, markers
// and filters stripped - the converter reads geometry and structure only.
export const FLOWCHART_SVG = `<svg id="m-flowchart" width="100%" xmlns="http://www.w3.org/2000/svg" class="flowchart" viewBox="0 0 399.03125 121.515625" role="graphics-document document" aria-roledescription="flowchart-v2"><g><g class="root"><g class="clusters"></g><g class="edgePaths"><path id="m-flowchart-L_A_B_0" class="flowchart-link" data-edge="true" data-et="edge" data-id="L_A_B_0" data-points="W3sieCI6MTAzLjAxNTYyNSwieSI6NjAuNzU3ODEyNX0seyJ4IjoxMzYuMzI4MTI1LCJ5Ijo2MC43NTc4MTI1fSx7IngiOjE2OS42NDA2MjUsInkiOjYwLjc1NzgxMjV9XQ=="></path><path id="m-flowchart-L_B_C_0" class="flowchart-link" data-edge="true" data-et="edge" data-id="L_B_C_0" data-points="W3sieCI6Mjc1LjE1NjI1LCJ5Ijo2MC43NTc4MTI1fSx7IngiOjMwMC4xNTYyNSwieSI6NjAuNzU3ODEyNX0seyJ4IjozMjUuMTU2MjUsInkiOjYwLjc1NzgxMjV9XQ=="></path></g><g class="edgeLabels"><g class="edgeLabel" transform="translate(136.328125, 60.7578125)"><g class="label" data-id="L_A_B_0" transform="translate(-8.3125, -12)"><foreignObject width="16.625" height="24"><div class="labelBkg"><span class="edgeLabel"><p>go</p></span></div></foreignObject></g></g><g class="edgeLabel"><g class="label" data-id="L_B_C_0" transform="translate(0, 0)"><foreignObject width="0" height="0"><div class="labelBkg"><span class="edgeLabel"></span></div></foreignObject></g></g></g><g class="nodes"><g class="node default" id="m-flowchart-flowchart-A-0" transform="translate(55.5078125, 60.7578125)"><rect class="basic label-container" x="-47.5078125" y="-27" width="95.015625" height="54"></rect><g class="label" transform="translate(-17.5078125, -12)"><rect></rect><foreignObject width="35.015625" height="24"><div><span class="nodeLabel"><p>Start</p></span></div></foreignObject></g></g><g class="node default" id="m-flowchart-flowchart-B-1" transform="translate(222.3984375, 60.7578125)"><polygon points="52.7578125,0 105.515625,-52.7578125 52.7578125,-105.515625 0,-52.7578125" class="label-container" transform="translate(-52.2578125, 52.7578125)"></polygon><g class="label" transform="translate(-25.7578125, -12)"><rect></rect><foreignObject width="51.515625" height="24"><div><span class="nodeLabel"><p>Ship it?</p></span></div></foreignObject></g></g><g class="node default" id="m-flowchart-flowchart-C-3" transform="translate(358.09375, 60.7578125)"><rect class="basic label-container" rx="5" ry="5" x="-32.9375" y="-27" width="65.875" height="54"></rect><g class="label" transform="translate(-17.9375, -12)"><rect></rect><foreignObject width="35.875" height="24"><div><span class="nodeLabel"><p>Done</p></span></div></foreignObject></g></g></g></g></g></svg>`

// A subgraph nests a second `g.root`, so its members are positioned relative
// to that group rather than to the diagram.
export const SUBGRAPH_SVG = `<svg id="m-subgraph" width="100%" xmlns="http://www.w3.org/2000/svg" class="flowchart" viewBox="0 0 341.828125 140" role="graphics-document document" aria-roledescription="flowchart-v2"><g><g class="root"><g class="clusters"></g><g class="edgePaths"></g><g class="edgeLabels"></g><g class="nodes"><g class="root" transform="translate(0, 0)"><g class="clusters"><g class="cluster" id="m-subgraph-S"><rect x="8" y="8" width="325.828125" height="124"></rect><g class="cluster-label" transform="translate(149.2734375, 8)"><foreignObject width="43.28125" height="24"><div><span class="nodeLabel"><p>Group</p></span></div></foreignObject></g></g></g><g class="edgePaths"><path id="m-subgraph-L_A_B_0" class="flowchart-link" data-edge="true" data-et="edge" data-id="L_A_B_0" data-points="W3sieCI6MTMzLjc1LCJ5Ijo3MH0seyJ4IjoxNzEuMjUsInkiOjcwfSx7IngiOjIwOC43NSwieSI6NzB9XQ=="></path></g><g class="edgeLabels"><g class="edgeLabel"><g class="label" data-id="L_A_B_0" transform="translate(0, 0)"><foreignObject width="0" height="0"><div class="labelBkg"><span class="edgeLabel"></span></div></foreignObject></g></g></g><g class="nodes"><g class="node default" id="m-subgraph-flowchart-A-0" transform="translate(89.625, 70)"><rect class="basic label-container" x="-44.125" y="-27" width="88.25" height="54"></rect><g class="label" transform="translate(-14.125, -12)"><rect></rect><foreignObject width="28.25" height="24"><div><span class="nodeLabel"><p>One</p></span></div></foreignObject></g></g><g class="node default" id="m-subgraph-flowchart-B-1" transform="translate(252.5390625, 70)"><rect class="basic label-container" x="-43.7890625" y="-27" width="87.578125" height="54"></rect><g class="label" transform="translate(-13.7890625, -12)"><rect></rect><foreignObject width="27.578125" height="24"><div><span class="nodeLabel"><p>Two</p></span></div></foreignObject></g></g></g></g></g></g></g></svg>`

export const SPECIAL_CHARACTERS_SVG = `<svg id="m-special" width="100%" xmlns="http://www.w3.org/2000/svg" class="flowchart" viewBox="0 0 302.5 70" role="graphics-document document" aria-roledescription="flowchart-v2"><g><g class="root"><g class="clusters"></g><g class="edgePaths"><path id="m-special-L_A_B_0" class="flowchart-link" data-edge="true" data-et="edge" data-id="L_A_B_0" data-points="W3sieCI6MTMyLjIxODc1LCJ5IjozNX0seyJ4IjoxNTcuMjE4NzUsInkiOjM1fSx7IngiOjE4Mi4yMTg3NSwieSI6MzV9XQ=="></path></g><g class="edgeLabels"><g class="edgeLabel"><g class="label" data-id="L_A_B_0" transform="translate(0, 0)"><foreignObject width="0" height="0"><div class="labelBkg"><span class="edgeLabel"></span></div></foreignObject></g></g></g><g class="nodes"><g class="node default" id="m-special-flowchart-A-0" transform="translate(70.109375, 35)"><rect class="basic label-container" x="-62.109375" y="-27" width="124.21875" height="54"></rect><g class="label" transform="translate(-32.109375, -12)"><rect></rect><foreignObject width="64.21875" height="24"><div><span class="nodeLabel"><p>a &lt; b &amp; c</p></span></div></foreignObject></g></g><g class="node default" id="m-special-flowchart-B-1" transform="translate(238.359375, 35)"><rect class="basic label-container" x="-56.140625" y="-27" width="112.28125" height="54"></rect><g class="label" transform="translate(-26.140625, -12)"><rect></rect><foreignObject width="52.28125" height="24"><div><span class="nodeLabel"><p>say "hi"</p></span></div></foreignObject></g></g></g></g></g></svg>`

// Stands in for every diagram type without a native mapping.
export const SEQUENCE_SVG = `<svg id="m-sequence" xmlns="http://www.w3.org/2000/svg" viewBox="-50 -10 450 300" role="graphics-document document" aria-roledescription="sequence"><g><text class="actor">Alice</text></g></svg>`
