// Regenerates src/lib/text-tools/dictionaries/technical-terms.generated.ts from
// @cspell/dict-software-terms. Run by hand (`pnpm dictionaries:generate`, then
// `pnpm lint` to fix the double-quoted strings `JSON.stringify` writes) when
// that package updates - not part of the regular build, since the wordlist
// rarely changes and the package itself is a devDependency only, never
// shipped. Written as a plain TS module (a string array) rather than a `?raw`
// text import: a project-relative `?raw` import is invisible to knip's
// resolver, where a real module is not. See technical-terms.ts for how the
// output gets spliced into a Hunspell dictionary.
//
// Run directly with `node` - Node strips this file's types rather than
// transpiling them, which is why `tsconfig.node.json` (this script's project)
// turns on `erasableSyntaxOnly`: any construct Node can't just erase (an enum,
// a parameter property) would typecheck here and then fail at runtime.

import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gunzipSync } from 'node:zlib'

const require = createRequire(import.meta.url)
// The package's `exports` field only exposes `cspell-ext.json`, not its own
// `package.json`, so that's what has to be resolved to find the package's
// installed directory.
const packageDir = dirname(require.resolve('@cspell/dict-software-terms'))
const dictDir = join(packageDir, 'dict')

type Source = { file: string; gzip: boolean }

// The package's own default-enabled set (its cspell-ext.json), minus
// "software-term-suggestions" - that one maps typos to corrections rather
// than listing valid words, so splicing it in would add misspellings.
const SOURCES: Source[] = [
	{ file: 'softwareTerms.txt.gz', gzip: true },
	{ file: 'coding-compound-terms.txt', gzip: false },
	{ file: 'computing-acronyms.txt', gzip: false },
	{ file: 'software-tools.txt', gzip: false },
	{ file: 'webServices.txt', gzip: false },
]

// Cspell wordlists mix in syntax this project doesn't use: `*word*` compound
// fragments (not real standalone words), blank lines, and a `#`-prefixed
// header. Only a plain word/acronym survives.
const WORD_PATTERN = /^[A-Za-z][A-Za-z0-9'-]*$/

function readWords({ file, gzip }: Source): string[] {
	const bytes = readFileSync(join(dictDir, file))
	const text = gzip
		? gunzipSync(bytes).toString('utf8')
		: bytes.toString('utf8')

	return text
		.split('\n')
		.map((line) => line.trim())
		.filter((line) => WORD_PATTERN.test(line))
}

const words = [...new Set(SOURCES.flatMap(readWords))].sort()

const outPath = join(
	dirname(fileURLToPath(import.meta.url)),
	'../src/lib/text-tools/dictionaries/technical-terms.generated.ts'
)

const lines = [
	'// Generated by scripts/generate-technical-terms.ts - do not edit by hand.',
	'export const TECHNICAL_TERMS: string[] = [',
	...words.map((word) => `\t${JSON.stringify(word)},`),
	']',
	'',
]

writeFileSync(outPath, lines.join('\n'))

console.log(`Wrote ${words.length} terms to ${outPath}`)
